services:
  solr:
    # image: solr:10
    image: solr-rc:10.1.0-1
    ports:
      - "8983:8983"
    volumes:
      - ./solr_configs:/opt/solr/conf
      - ./solr_data:/var/solr
    environment:
      SOLR_JAVA_MEM: "-Xms256m -Xmx1024m"
    command:
      - solr-precreate
      - sdr-search
      - /opt/solr/conf
